### ISSUE TITLE
我说，淘宝那么多羊毛为何插件不搞，为什么就搞飞猪那点里程？

### ISSUE THREAD

**Issue by petcat** [sunoj/teaclub#19]
撸里程应该是信用卡吧。

淘宝里面好多羊毛的，希望插件跟进吧，

1、淘宝吃货频道，登陆就有券，2-3小券可以不理，万一刷到大额券插件可以提醒；里面还有抢鸡蛋，目前30个鸡蛋可以9.9领，还有些一分钱秒杀；

2、天猫美食频道，也可以插件代做任务；

3、充值中心频道，登陆可以一天一毛，累积可以领10-1, 20-2, 50-5的话费券，10%的充值优惠也是有用的，你想想京东那个逗逼90-2话费券；

4、芭芭农场频道，免费种水果，两个项目的，一个是合种，一个是采阳光，都可以免费换水果；

**Comment by sunoj** [comment]
你提到的这些似乎都不能在电脑浏览器打开
