### ISSUE TITLE
插件不工作

### ISSUE THREAD

**Issue by denniszzg** [sunoj/teaclub#2]
chrome版本：版本 72.0.3626.121（正式版本） （32 位）
茶友会版本：0.1.6

点插件左下角成功登陆淘宝后，刷新任务，并没有自动领取金币。
昨日安装插件至今，“最近通知”始终是空的。这是否意味着插件没有正常运行？

**Comment by sunoj** [comment]
可以点击任务标题直接打开任务页面，看是否正常执行

**Comment by denniszzg** [comment]
上午登陆后试了一下，显示“茶友会运行中”之后，一直没有反应，于是手动签到领金币，领取成功。

**Comment by sunoj** [comment]
目前的信息无法判断问题原因，不过可以尝试升级一下浏览器。

**Comment by denniszzg** [comment]
昨天升级chrome后没什么变化，今天点击金币庄园手动打开任务页面，成功自动打卡领取20淘金币。最近通知显示一条信息。
明日观察能否自动打开任务页面领取金币

**Comment by sunoj** [comment]
看样子是正常的
