### ISSUE TITLE
【建议】淘宝订单号每月可领15飞猪里程

### ISSUE THREAD

**Issue by sanhu88** [sunoj/teaclub#3]
url ： https://www.fliggy.com/mytrip/?tvm=tcd&orderId=xxxxxxxxxxxxx
xxxxxxxxxxxxx 代表单号，连没付款的都可以领到
每单3个里程，一个月内可以领5次
希望可以增加，感谢

**Comment by sunoj** [comment]
感谢建议，下一版加

**Comment by sunoj** [comment]
0.2.2 已有此功能
