### ISSUE TITLE
插件不工作

### ISSUE THREAD

**Issue by yangweijie** [sunoj/teaclub#5]
自动领取金币 不工作

**Comment by sunoj** [comment]
请补充细节

**Comment by yangweijie** [comment]
edge 浏览器 和家里的chrome 浏览器 安装好扩展后 登录pc  版淘宝后，  点击金币庄园 无法签到拿金币，而竞价宝 可以成功签到

**Comment by yangweijie** [comment]
edge 浏览器 和家里的chrome 浏览器 安装好扩展后 登录pc  版淘宝后，  点击金币庄园 无法签到拿金币，而竞价宝 可以成功签到

**Comment by yangweijie** [comment]
![image](https://user-images.githubusercontent.com/1614114/61198648-7d4b2180-a70d-11e9-9d18-d803db798d78.png)
配置频率是 每天

**Comment by sunoj** [comment]
从来没有领取到淘金币吗？

**Comment by yangweijie** [comment]
从来没有 自动手动 都没有

**Comment by sunoj** [comment]
手动点击一下任务名称，确认一下有没有可以领取的淘金币

**Comment by yangweijie** [comment]
点了同样的报错， 淘宝app上 显示有金币的 
![image](https://user-images.githubusercontent.com/1614114/61199386-57734c00-a710-11e9-89a0-772b475c6acb.png)

**Comment by sunoj** [comment]
请问“同样报错”是什么意思，点击任务的名称，应该会打开一个网页

**Comment by yangweijie** [comment]
点击任务 打开一个网页提示登录失效，重新登录后， 自动签到成功了 是你们登录状态监测 不正常吗？ 那为什么里程能正常领取。 还有金币领完了，为什么苹果没有收取金币

**Comment by sunoj** [comment]
无法根据个例来分析，但是感谢你提供的反馈。
